# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c2be65d3515d29d4b851e1c71890fe4ef64f3f0e679a35b5af21ede4a0323cea4c27d287bb67a1c70369ae11fb455c62c9389d780f9add6e10b8f9afdad24b

test:
  secret_key_base: a8b116bd6c3e99a1ecf70861ed086505a586faac33dbe1aea709fd9cb5684b34d36d7ae67cc5e3f8483d6328b306d4919a237add72a2f3757700678d658d0599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
